### ISSUE TITLE
Unable to connect to VNC via novnc

### ISSUE THREAD

**Issue by akzaidi** [ml-tooling/ml-workspace#13]
**Describe the bug:**

Attempts to connect to VNC desktop fail with the following error:

![image](https://user-images.githubusercontent.com/1307603/68081716-bba94100-fdcf-11e9-86e1-af7b18ebf278.png)

**Expected behaviour:**

Ability to view desktop via novnc 

**Steps to reproduce the issue:**

**Technical details:**

- Workspace version: `0.8.7` 
- Docker version: `3.0.6` 
- Host Machine OS (Windows/Linux/Mac): `Ubuntu 18.04`
- Command used to start the workspace:
```bash
docker run \
        -p 8080:8080 \
        --name "ml-workspace" \
        --env AUTHENTICATE_VIA_JUPYTER="######" \
        --shm-size 56G mltooling/ml-workspace:latest
```
- Browser (Chrome/Firefox/Safari):Chrome

**Possible Fix:**

Wish I knew!

**Additional context:**

Thanks a lot for providing this wonderful tool! Has been immensely helpful already.

**Comment by lukasmasuch** [comment]
Thanks for reporting this issue! I assume that noVNC itself is working fine, but Xfce fails to display the Desktop because of some AppArmor configurations on your Host system which is preventing interactions with the DBus daemon. Docker uses AppArmor to prevent security threats by denying applications within containers access to certain host resources and capabilities, as explained [here](https://docs.docker.com/engine/security/apparmor/). In the default Docker AppArmor configuration and all cloud providers that we have tested the workspace on, the XFCE Desktop is running fine. To help you out with the issue, we would need a few additional information:

1) Do you have more information on the host server that the workspace was deployed on? Do you use any cloud provider, or is it a local server? Do you have an admin account on the server?

2) Do you know of any custom AppArmor configuration on the host system?

3) Can you try to run the workspace with this docker run option to evaluate if an AppArmor policy is preventing Xfce from starting the Desktop GUI: `--security-opt "apparmor:unconfined"`

4) Is there any GUI (e.g., Xfce, Gnome...) installed and/or running on the server?
