### ISSUE TITLE
Trying to customize dockerfile for company use.

### ISSUE THREAD

**Issue by krishna-anand** [ml-tooling/ml-workspace#24]
**Describe the issue:**
Unable to build dockerfile and continually returns errors repeatedly. 

Simply just trying to build the dockerfile while adding one extension that we have created into the dockerfile to have set up upon launching jupyterlab. Any help would be really appreciated. 
![Screen Shot 2020-01-07 at 4 41 03 PM](https://user-images.githubusercontent.com/39285689/72001374-33458300-31fa-11ea-8ce3-a0f9cb434f1a.png)
![Screen Shot 2020-01-08 at 9 35 36 AM](https://user-images.githubusercontent.com/39285689/72001402-422c3580-31fa-11ea-9bbc-0546836f62fa.png)

**Technical details:**

- Workspace version : 
- Docker version <Docker 2.1.0.5 >: 
- Host Machine OS (Mac): 
- Command used to start the workspace :
- Browser (Chrome):

**Comment by IslamAlam** [comment]
The current docker files are broken due to pip dependencies and Nginx Openresty version. 
This branch includes a fix for the issue:
https://github.com/IslamAlam/ml-workspace/tree/develop-eo

After testing that everything is working later, I will provide a pull request.

It is published here in case you need the build itself. 
https://hub.docker.com/r/imansour/ml-workspace

**Comment by krishna-anand** [comment]
thank you so much!

**Comment by krishna-anand** [comment]
> The current docker files are broken due to pip dependencies and Nginx Openresty version.
> This branch includes a fix for the issue:
> https://github.com/IslamAlam/ml-workspace/tree/develop-eo
> 
> After testing that everything is working later, I will provide a pull request.
> 
> It is published here in case you need the build itself.
> https://hub.docker.com/r/imansour/ml-workspace

<img width="728" alt="Screen Shot 2020-01-09 at 9 22 55 AM" src="https://user-images.githubusercontent.com/39285689/72089829-a0701b80-32c1-11ea-833b-157968a820b7.png">

i also had the following error

**Comment by IslamAlam** [comment]
I have tested this release on the develop branch:
https://github.com/IslamAlam/ml-workspace/releases/tag/0.1.1

Could you check out this commit and build it once more?
Just in case, I had some issue with building the image with docker, after I had a clean build, no issue.

**Comment by lukasmasuch** [comment]
@krishna-anand I did lots of fixes and updates during the last days. The current state of the workspace (develop branch) should be fully buildable again. A stable version will be released within the next few days. Does the current state build for you?

For customizing the workspace, I suggest to just extend from the last stable workspace version and add apply your changes within a new Dockerfile as explained in the [FAQ](https://github.com/ml-tooling/ml-workspace#faq). Building the workspace from scratch can be very time consuming since there are tons of dependencies that can break.
