### ISSUE TITLE
Error when attempting to install dependencies from conda environment.yml

### ISSUE THREAD

**Issue by tbrassel** [ml-tooling/ml-workspace#29]
**Describe the bug:**
---------------------

-   Directly adding a environment.yml package to my code directory does
    not automatically install the correct dependencies.

**Expected behaviour:**
-----------------------

-   I install various dependencies including pip dependent packages to
    conda environments as part of my machine learning workflows. Based
    on my uncertain understanding of “Installing Dependencies”
    instructions, I expect that if I add a conda environment.yml to the
    directory from which I run the docker container the docker container
    will use the environment.yml file to initialize the base conda
    environment.

**Steps to reproduce the issue:**
---------------------------------

1.  Use conda to generate a environment.yml file from an existing conda
    environment with additional pip installed packages.
2.  Add this file to a specific home directory in which you want to
    work: /user/home/folder\_to\_use
3.  cd into this directory and run the following start command:
    `sudo docker run -d -p 8080:8080 --gpus all --name "ml-workspace" -v "${PWD}:/workspace" --env AUTHENTICATE_VIA_JUPYTER="mytoken" --shm-size 512m --restart=no mltooling/ml-workspace-gpu:latest`
4.  Navigate to the virtual desktop and start VSCode. The python
    environment does not appear in the options menu.

**Technical details:**
----------------------

-   Workspace version: 0.9.1
-   Docker version: 19.03.05
-   Host Machine OS (Windows/Linux/Mac): Ubuntu 18.04
-   Command used to start the workspace:
    `sudo docker run -d -p 8080:8080 --gpus all --name "ml-workspace" -v "${PWD}:/workspace" --env AUTHENTICATE_VIA_JUPYTER="mytoken" --shm-size 512m --restart=no mltooling/ml-workspace-gpu:latest`
-   Browser (Chrome/Firefox/Safari): Firefox

**Possible Fix:**
-----------------

-   Rebuild the docker file with the necessary packages and channels
    hardcoded in.

**Additional context:**
-----------------------

-   I fully acknowledge that I am most likely missing something. What is
    the proper way to install various dependencies to the workspace
    besides editing the dockerfile?

**Comment by lukasmasuch** [comment]
@tbrassel The `Install Dependencies` section is related to running code via the workspace container without starting any interactive tools. In the normal usage, the `environment.yml` is currently not installed automatically (we might consider that in the future). When you start the workspace, it is somewhat like a virtual machine running on you computer with its own OS, installed libraries and tools. 

The beste way to install additional dependencies is by just using the terminal within the workspace (find out more in the [extensibility section](https://github.com/ml-tooling/ml-workspace#extensibility)). So, you can just create a new conda environment from your environment.yml as explained [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file). VS-code should automatically discover this new environment. If you like to use Jupyter, just use `ipykernel` to install a kernel in the given environemnt as explained [here](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments). 

However, since the base conda environment of the workspace already comes preinstalled with many of the most commonly used libraries, you might not even have to install your `environment.yml` (depending on the complexity of your dependencies). I mostly manage my project dependencies within a `requirements.txt` which I install via pip within the base conda environment of the workspace.
