### ISSUE TITLE
Delete master branch?

### ISSUE THREAD

**Issue by yarikoptic** [ml-tooling/ml-workspace#60]
Having both master and main is confusing.  I have initiated a PR first from master then only to arrive to conflicts.  If `master` is no longer used, best would be just to remove that branch `git push origin :master` to avoid confusion etc

**Comment by lukasmasuch** [comment]
Hey @yarikoptic, thanks for the hint. The reason I kept `master` for a few more days after changing to `main` was because we have linked some files/images on external sites (e.g. on Dockerhub) with `master` in the link. I still have to check a few locations, but will delete the branch in the next days.

**Comment by lukasmasuch** [comment]
Master branch is deleted now
