### ISSUE TITLE
Is it supported on mac m1?

### ISSUE THREAD

**Issue by winglight** [ml-tooling/ml-workspace#97]
**Describe the bug:**
I got a tip icon of docker desktop on mac m1: amd64, is there any possible to support mac m1 natively?

**Comment by raethlein** [comment]
We have not tested it on the M1 Mac or any other ARM machine so far. [Here is a Medium article](https://medium.com/nttlabs/buildx-multiarch-2c6c2df00ca2) that explains how to cross-compile images but unfortunately I didn't find time yet to play around with it. Since M1 Macs / ARM machines will grow in numbers in the future, we definitely have to spend some time to offer future images for both architectures in case they don't work out of the box.
Also, do you mean with "natively" without Rosetta2? Because otherwise [this post](https://docs.docker.com/docker-for-mac/apple-silicon/) might help you to run the container. Unfortunately, I cannot test it myself.

**Comment by MohamedElashri** [comment]
The solution will be to build the image first on your M1. In the future I would like to have an ARM build included in docker hub.  Keep in mind that `Dockefile` needs multiple changes for this to be done.


I'm trying to do this build and this issue will be a good place to keep track of the modification needed and potential problems. 

-  We need to change miniconda version from `Linux-x86_64` to `Linux-aarch64.`. Trivial and neat, thank miniconda they have a build for arm for the same version 

-  tigervnc is an x86-64 based, so we want to change that. Thankfully arch Linux community have version available at ` http://mirror.archlinuxarm.org/aarch64/community/tigervnc-1.11.0-6-aarch64.pkg.tar.xz` so we should change that in `Dockerfile` line 472. 

-  klogg does not work on arm64 and no build is available.  I think going to `glogg` is a solution but didn't try it yet 
https://debian.pkgs.org/11/debian-main-arm64/glogg_1.1.4-1.1+b4_arm64.deb.html

We will need to install `libqt5gui5-gles`, `libboost-program-options`, `libqt5dbus5` and `libqt5core5a ` because they needed 

- Other things I did not get to yet

Hint: this is not a bug issue as this is docker behavior. Docker images built on certain architecture do not generally on others.

**Comment by raethlein** [comment]
Awesome, thanks @MohamedElashri already for the first examination. One aspect to also consider besides the tools are the libraries. I am uncertain whether libs such as tensorflow or pytorch work out-of-the-box on ARM. For example, there is this [tensorflow-for-arm](https://github.com/lhelontra/tensorflow-on-arm) repo or this unofficial [pytorch-arm-builds](https://github.com/nmilosev/pytorch-arm-builds) repo. This might hint to the fact that the "normal" versions don't work on ARM; though I might be wrong about that.

**Comment by MohamedElashri** [comment]
> Awesome, thanks @MohamedElashri already for the first examination. One aspect to also consider besides the tools are the libraries. I am uncertain whether libs such as tensorflow or pytorch work out-of-the-box on ARM. For example, there is this [tensorflow-for-arm](https://github.com/lhelontra/tensorflow-on-arm) repo or this unofficial [pytorch-arm-builds](https://github.com/nmilosev/pytorch-arm-builds) repo. This might hint to the fact that the "normal" versions don't work on ARM; though I might be wrong about that.


That's a valid concern for this project scope but not a very deep problem. I think publishing this container doesn't need to initially have all pre-installed libraries which could be solved via manual installation via Jupyterhub/Jupyter Notebook in general which would keep things easier for maintaining as every day support for ARM libraries comes with workarounds and support from different projects. 

I think for adding ARM support we can go the minimal way. Making sure that tools are working (maybe replace unsupported or try later to have ARM build for them) and the more fundamental libraries having support like `numpy` and `matplotlib` already on arm64. But in general I agree with you that "normal" version does not work on ARM, so things are not a problem of cross build or just build on arm machine and everything will work out of the box. 

I would like to work on that but honestly don't know the scope of what we could achieve and if you would mind having different (potentially fewer features) ARM version.

**Comment by MohamedElashri** [comment]
I have a problem with `fix-permission.sh` script which should read `USER_GID` from the Dockerfile already, but it is not, and I get stuck at `Please set a user GID via USER_GID env varibale.` with `return error 1` I don't know what should be the problem here

**Comment by raethlein** [comment]
Do you get that error with the unmodified Dockerfile or have you already modified it? As you said, the `USER_GID` is set in the Dockerfile on the very top and I have so far never experience that issue.

**Comment by MohamedElashri** [comment]
I get past this point although I did not know what was the problem but it is now solved. Still trying to tackle compatibility issues.
